In [3]:
import os 
import requests
from dotenv import load_dotenv
import pandas as pd

load_dotenv()

API_KEY = os.getenv("ALPHA_VANTAGE_API_KEY") #get API key from env file

BASE_URL = "https://www.alphavantage.co/query" #base url for api

def fetch_stock_data(symbol):
    
    """
    Fetch daily stock data from Alpha API
    """

    
    params = {
        "function" : "TIME_SERIES_DAILY",
        "symbol": symbol,
        "apikey" : API_KEY 
    }

    response = requests.get(BASE_URL, params=params)
    
    if response.status_code != 200 :
        raise Exception("API request dailed")

   
    data = response.json() 
    
    if "Error Message" in data:
        raise Exception("Invalid API call")

    if "Note" in data:
        raise Exception("API rate limit exceeded")

    return data 

def parse_stock_data(data) :
    """
    Extract time serise data from API response
    """

    if "Time Series (Daily)" not in data:
        raise Exception("Time Series data not found in API response")
    
    return data["Time Series (Daily)"]

import pandas as pd

def convert_to_df(df) :
    return pd.DataFrame(df).T


def time_serise_analysis_dataset (df) :
    df = df.copy() #copy this dataset so that for delink the referance 
    df = df.drop_duplicates() #drop the duplicate value
    df = df.dropna()  #drop the missing value KAN-39
    df = df.rename(columns={                            
            "1. open" :"open",
            "2. high" :"high" ,  
            "3. low"  :"low" , 
            "4. close" :"close"  ,
            "5. volume" : "volume" }) #rename the column
    df = df.astype({"open":float,"high":float,"low":float,"close":float,"volume":int}).round(2) #reasign the data type and round it by 2

    df.index = pd.to_datetime(df.index) #set index value as date time
    
    df = df.sort_index(ascending=False) # sorted the index

    df.reset_index(inplace=True)
    df.rename(columns={"index":"Date"},inplace=True) #change the index name as date 
    df = df.set_index("Date") #set this cloumn as date time 
    return df
def time_serise_feature_engineering(df) :
    
    df["close_norm"] = (df["close"] /  df["close"].max()).astype(float).round(2)  #normalized this stock value KAN-40 


    df["retuens"] = (df["close"].pct_change().fillna(0)).astype(float).round(4) #calculatethe daily return KAN-41

        

    df["pct_change"] = (df["close"].pct_change().fillna(0) * 100).astype(float).round(2) #calculate the percentage chnage
    
    return df


def compute_all_statistics(df) :
    stats = {}

    # core return stats
    stats["mean"] = round(float(df["retuens"].mean()),6)
    stats["median"] = round(float(df["retuens"].median()),6)
    stats["std_dev"] = round(float(df["retuens"].std()),6)
    stats["variance"] =  round(float(df["retuens"].var()),6)

    # Extremes
    stats["min"] =  round(float(df["retuens"].min()),6)
    stats["max"] =  round(float(df["retuens"].max()),6)

    #Percentiles
    stats["percentiles"] = {
        "25" :round(float(df["retuens"].quantile(0.25)),6),
        "50" :round(float(df["retuens"].quantile(0.50)),6),
        "75" :round(float(df["retuens"].quantile(0.75)),6),
        "5"  :round(float(df["retuens"].quantile(0.05)),6),
        "95" :round(float(df["retuens"].quantile(0.95)),6),

    }

    return stats

In [4]:
def get_stock_analysis(symbol) :

     data = fetch_stock_data(symbol)  #get the overall stock data
     time_series = parse_stock_data(data) #get the time series data
     time_series_data_frame = convert_to_df(time_series) #convert to the dataframe
     time_series_data_frame = time_serise_analysis_dataset(time_series_data_frame)
     time_series_data_frame = time_serise_feature_engineering(time_series_data_frame)  # create analysis data
     
     stats = compute_all_statistics(time_series_data_frame)  #Extract the stats out of it 

     return {
          "symbol" : symbol ,
          "stats" : stats,
          "Data": time_series_data_frame , #return only the first 10 records for now
          
     }

In [5]:
data = get_stock_analysis("AAPL")
symbol = data["symbol"]
final_output = data["Data"]

final_output.keys()

Index(['open', 'high', 'low', 'close', 'volume', 'close_norm', 'retuens',
       'pct_change'],
      dtype='str')

In [6]:
final_output.head()

,open,high,low,close,volume,close_norm,retuens,pct_change
Date,,,,,,,,
2026-03-27,253.90,255.49,248.07,248.80,47899998,0.87,0.0000,0.00
2026-03-26,252.12,257.00,250.77,252.89,41796650,0.88,0.0164,1.64
2026-03-25,254.10,255.00,251.60,252.62,28476668,0.88,-0.0011,-0.11
2026-03-24,250.35,254.82,249.55,251.64,45152288,0.88,-0.0039,-0.39
2026-03-23,253.97,254.60,250.28,251.49,40546109,0.88,-0.0006,-0.06

In [7]:
# latest_date = "2026-03-23"

In [8]:
# new_df = final_output[final_output.index > latest_date]

In [9]:
# type(new_df.index[0])

In [10]:
records= []

for date, row in final_output.iterrows() :
    records.append({
        "date": date.strftime("%Y-%m-%d"),
        "open" : float(row["open"])
    })

In [11]:
records

[{'date': '2026-03-27', 'open': 253.9},
 {'date': '2026-03-26', 'open': 252.12},
 {'date': '2026-03-25', 'open': 254.1},
 {'date': '2026-03-24', 'open': 250.35},
 {'date': '2026-03-23', 'open': 253.97},
 {'date': '2026-03-20', 'open': 247.98},
 {'date': '2026-03-19', 'open': 249.4},
 {'date': '2026-03-18', 'open': 252.62},
 {'date': '2026-03-17', 'open': 252.96},
 {'date': '2026-03-16', 'open': 252.1},
 {'date': '2026-03-13', 'open': 255.48},
 {'date': '2026-03-12', 'open': 258.66},
 {'date': '2026-03-11', 'open': 261.09},
 {'date': '2026-03-10', 'open': 257.64},
 {'date': '2026-03-09', 'open': 255.69},
 {'date': '2026-03-06', 'open': 258.63},
 {'date': '2026-03-05', 'open': 260.79},
 {'date': '2026-03-04', 'open': 264.65},
 {'date': '2026-03-03', 'open': 263.48},
 {'date': '2026-03-02', 'open': 262.41},
 {'date': '2026-02-27', 'open': 272.81},
 {'date': '2026-02-26', 'open': 274.94},
 {'date': '2026-02-25', 'open': 271.78},
 {'date': '2026-02-24', 'open': 267.86},
 {'date': '2026-02-23', 'open': 263.49},
 {'date': '2026-02-20', 'open': 258.97},
 {'date': '2026-02-19', 'open': 262.6},
 {'date': '2026-02-18', 'open': 263.6},
 {'date': '2026-02-17', 'open': 258.05},
 {'date': '2026-02-13', 'open': 262.01},
 {'date': '2026-02-12', 'open': 275.59},
 {'date': '2026-02-11', 'open': 274.7},
 {'date': '2026-02-10', 'open': 274.88},
 {'date': '2026-02-09', 'open': 277.9},
 {'date': '2026-02-06', 'open': 277.12},
 {'date': '2026-02-05', 'open': 278.13},
 {'date': '2026-02-04', 'open': 272.29},
 {'date': '2026-02-03', 'open': 269.2},
 {'date': '2026-02-02', 'open': 260.03},
 {'date': '2026-01-30', 'open': 255.16},
 {'date': '2026-01-29', 'open': 258.0},
 {'date': '2026-01-28', 'open': 257.65},
 {'date': '2026-01-27', 'open': 259.17},
 {'date': '2026-01-26', 'open': 251.48},
 {'date': '2026-01-23', 'open': 247.32},
 {'date': '2026-01-22', 'open': 249.2},
 {'date': '2026-01-21', 'open': 248.7},
 {'date': '2026-01-20', 'open': 252.73},
 {'date': '2026-01-16', 'open': 257.9},
 {'date': '2026-01-15', 'open': 260.65},
 {'date': '2026-01-14', 'open': 259.49},
 {'date': '2026-01-13', 'open': 258.72},
 {'date': '2026-01-12', 'open': 259.16},
 {'date': '2026-01-09', 'open': 259.08},
 {'date': '2026-01-08', 'open': 257.02},
 {'date': '2026-01-07', 'open': 263.2},
 {'date': '2026-01-06', 'open': 267.0},
 {'date': '2026-01-05', 'open': 270.64},
 {'date': '2026-01-02', 'open': 272.26},
 {'date': '2025-12-31', 'open': 273.06},
 {'date': '2025-12-30', 'open': 272.81},
 {'date': '2025-12-29', 'open': 272.69},
 {'date': '2025-12-26', 'open': 274.16},
 {'date': '2025-12-24', 'open': 272.34},
 {'date': '2025-12-23', 'open': 270.84},
 {'date': '2025-12-22', 'open': 272.86},
 {'date': '2025-12-19', 'open': 272.14},
 {'date': '2025-12-18', 'open': 273.6},
 {'date': '2025-12-17', 'open': 275.01},
 {'date': '2025-12-16', 'open': 272.82},
 {'date': '2025-12-15', 'open': 280.15},
 {'date': '2025-12-12', 'open': 277.9},
 {'date': '2025-12-11', 'open': 279.1},
 {'date': '2025-12-10', 'open': 277.75},
 {'date': '2025-12-09', 'open': 278.16},
 {'date': '2025-12-08', 'open': 278.13},
 {'date': '2025-12-05', 'open': 280.54},
 {'date': '2025-12-04', 'open': 284.1},
 {'date': '2025-12-03', 'open': 286.2},
 {'date': '2025-12-02', 'open': 283.0},
 {'date': '2025-12-01', 'open': 278.01},
 {'date': '2025-11-28', 'open': 277.26},
 {'date': '2025-11-26', 'open': 276.96},
 {'date': '2025-11-25', 'open': 275.27},
 {'date': '2025-11-24', 'open': 270.9},
 {'date': '2025-11-21', 'open': 265.95},
 {'date': '2025-11-20', 'open': 270.83},
 {'date': '2025-11-19', 'open': 265.52},
 {'date': '2025-11-18', 'open': 269.99},
 {'date': '2025-11-17', 'open': 268.82},
 {'date': '2025-11-14', 'open': 271.05},
 {'date': '2025-11-13', 'open': 274.11},
 {'date': '2025-11-12', 'open': 275.0},
 {'date': '2025-11-11', 'open': 269.81},
 {'date': '2025-11-10', 'open': 268.96},
 {'date': '2025-11-07', 'open': 269.8},
 {'date': '2025-11-06', 'open': 267.89},
 {'date': '2025-11-05', 'open': 268.61},
 {'date': '2025-11-04', 'open': 268.32},
 {'date': '2025-11-03', 'open': 270.42}]

In [12]:
final_output

,open,high,low,close,volume,close_norm,retuens,pct_change
Date,,,,,,,,
2026-03-27,253.90,255.49,248.07,248.80,47899998,0.87,0.0000,0.00
2026-03-26,252.12,257.00,250.77,252.89,41796650,0.88,0.0164,1.64
2026-03-25,254.10,255.00,251.60,252.62,28476668,0.88,-0.0011,-0.11
2026-03-24,250.35,254.82,249.55,251.64,45152288,0.88,-0.0039,-0.39
2026-03-23,253.97,254.60,250.28,251.49,40546109,0.88,-0.0006,-0.06
...,...,...,...,...,...,...,...,...
2025-11-07,269.80,272.29,266.77,268.47,48227365,0.94,-0.0036,-0.36
2025-11-06,267.89,273.40,267.89,269.77,51204045,0.94,0.0048,0.48
2025-11-05,268.61,271.70,266.93,270.14,42586288,0.94,0.0014,0.14
2025-11-04,268.32,271.49,267.62,270.04,49274846,0.94,-0.0004,-0.04
2025-11-03,270.42,270.85,266.25,269.05,50194583,0.94,-0.0037,-0.37

In [13]:
final_output.head()

,open,high,low,close,volume,close_norm,retuens,pct_change
Date,,,,,,,,
2026-03-27,253.90,255.49,248.07,248.80,47899998,0.87,0.0000,0.00
2026-03-26,252.12,257.00,250.77,252.89,41796650,0.88,0.0164,1.64
2026-03-25,254.10,255.00,251.60,252.62,28476668,0.88,-0.0011,-0.11
2026-03-24,250.35,254.82,249.55,251.64,45152288,0.88,-0.0039,-0.39
2026-03-23,253.97,254.60,250.28,251.49,40546109,0.88,-0.0006,-0.06

In [14]:
final_output.index = final_output.index.strftime("%Y-%m-%d")

In [15]:
latest_date = "2026-03-23"

In [21]:
print(final_output[final_output.index > latest_date])

              open    high     low   close    volume  close_norm  retuens  \
Date
2026-03-27  253.90  255.49  248.07  248.80  47899998        0.87   0.0000
2026-03-26  252.12  257.00  250.77  252.89  41796650        0.88   0.0164
2026-03-25  254.10  255.00  251.60  252.62  28476668        0.88  -0.0011
2026-03-24  250.35  254.82  249.55  251.64  45152288        0.88  -0.0039

            pct_change
Date
2026-03-27        0.00
2026-03-26        1.64
2026-03-25       -0.11
2026-03-24       -0.39

In [34]:
records = []
for Date, row in final_output.iterrows() :
    records.append({
        "Date" : Date,
        "Open":float(row["open"]),
        "Close" : float(row["open"]),
    })

In [35]:
records

[{'Date': '2026-03-27', 'Open': 253.9, 'Close': 253.9},
 {'Date': '2026-03-26', 'Open': 252.12, 'Close': 252.12},
 {'Date': '2026-03-25', 'Open': 254.1, 'Close': 254.1},
 {'Date': '2026-03-24', 'Open': 250.35, 'Close': 250.35},
 {'Date': '2026-03-23', 'Open': 253.97, 'Close': 253.97},
 {'Date': '2026-03-20', 'Open': 247.98, 'Close': 247.98},
 {'Date': '2026-03-19', 'Open': 249.4, 'Close': 249.4},
 {'Date': '2026-03-18', 'Open': 252.62, 'Close': 252.62},
 {'Date': '2026-03-17', 'Open': 252.96, 'Close': 252.96},
 {'Date': '2026-03-16', 'Open': 252.1, 'Close': 252.1},
 {'Date': '2026-03-13', 'Open': 255.48, 'Close': 255.48},
 {'Date': '2026-03-12', 'Open': 258.66, 'Close': 258.66},
 {'Date': '2026-03-11', 'Open': 261.09, 'Close': 261.09},
 {'Date': '2026-03-10', 'Open': 257.64, 'Close': 257.64},
 {'Date': '2026-03-09', 'Open': 255.69, 'Close': 255.69},
 {'Date': '2026-03-06', 'Open': 258.63, 'Close': 258.63},
 {'Date': '2026-03-05', 'Open': 260.79, 'Close': 260.79},
 {'Date': '2026-03-04', 'Open': 264.65, 'Close': 264.65},
 {'Date': '2026-03-03', 'Open': 263.48, 'Close': 263.48},
 {'Date': '2026-03-02', 'Open': 262.41, 'Close': 262.41},
 {'Date': '2026-02-27', 'Open': 272.81, 'Close': 272.81},
 {'Date': '2026-02-26', 'Open': 274.94, 'Close': 274.94},
 {'Date': '2026-02-25', 'Open': 271.78, 'Close': 271.78},
 {'Date': '2026-02-24', 'Open': 267.86, 'Close': 267.86},
 {'Date': '2026-02-23', 'Open': 263.49, 'Close': 263.49},
 {'Date': '2026-02-20', 'Open': 258.97, 'Close': 258.97},
 {'Date': '2026-02-19', 'Open': 262.6, 'Close': 262.6},
 {'Date': '2026-02-18', 'Open': 263.6, 'Close': 263.6},
 {'Date': '2026-02-17', 'Open': 258.05, 'Close': 258.05},
 {'Date': '2026-02-13', 'Open': 262.01, 'Close': 262.01},
 {'Date': '2026-02-12', 'Open': 275.59, 'Close': 275.59},
 {'Date': '2026-02-11', 'Open': 274.7, 'Close': 274.7},
 {'Date': '2026-02-10', 'Open': 274.88, 'Close': 274.88},
 {'Date': '2026-02-09', 'Open': 277.9, 'Close': 277.9},
 {'Date': '2026-02-06', 'Open': 277.12, 'Close': 277.12},
 {'Date': '2026-02-05', 'Open': 278.13, 'Close': 278.13},
 {'Date': '2026-02-04', 'Open': 272.29, 'Close': 272.29},
 {'Date': '2026-02-03', 'Open': 269.2, 'Close': 269.2},
 {'Date': '2026-02-02', 'Open': 260.03, 'Close': 260.03},
 {'Date': '2026-01-30', 'Open': 255.16, 'Close': 255.16},
 {'Date': '2026-01-29', 'Open': 258.0, 'Close': 258.0},
 {'Date': '2026-01-28', 'Open': 257.65, 'Close': 257.65},
 {'Date': '2026-01-27', 'Open': 259.17, 'Close': 259.17},
 {'Date': '2026-01-26', 'Open': 251.48, 'Close': 251.48},
 {'Date': '2026-01-23', 'Open': 247.32, 'Close': 247.32},
 {'Date': '2026-01-22', 'Open': 249.2, 'Close': 249.2},
 {'Date': '2026-01-21', 'Open': 248.7, 'Close': 248.7},
 {'Date': '2026-01-20', 'Open': 252.73, 'Close': 252.73},
 {'Date': '2026-01-16', 'Open': 257.9, 'Close': 257.9},
 {'Date': '2026-01-15', 'Open': 260.65, 'Close': 260.65},
 {'Date': '2026-01-14', 'Open': 259.49, 'Close': 259.49},
 {'Date': '2026-01-13', 'Open': 258.72, 'Close': 258.72},
 {'Date': '2026-01-12', 'Open': 259.16, 'Close': 259.16},
 {'Date': '2026-01-09', 'Open': 259.08, 'Close': 259.08},
 {'Date': '2026-01-08', 'Open': 257.02, 'Close': 257.02},
 {'Date': '2026-01-07', 'Open': 263.2, 'Close': 263.2},
 {'Date': '2026-01-06', 'Open': 267.0, 'Close': 267.0},
 {'Date': '2026-01-05', 'Open': 270.64, 'Close': 270.64},
 {'Date': '2026-01-02', 'Open': 272.26, 'Close': 272.26},
 {'Date': '2025-12-31', 'Open': 273.06, 'Close': 273.06},
 {'Date': '2025-12-30', 'Open': 272.81, 'Close': 272.81},
 {'Date': '2025-12-29', 'Open': 272.69, 'Close': 272.69},
 {'Date': '2025-12-26', 'Open': 274.16, 'Close': 274.16},
 {'Date': '2025-12-24', 'Open': 272.34, 'Close': 272.34},
 {'Date': '2025-12-23', 'Open': 270.84, 'Close': 270.84},
 {'Date': '2025-12-22', 'Open': 272.86, 'Close': 272.86},
 {'Date': '2025-12-19', 'Open': 272.14, 'Close': 272.14},
 {'Date': '2025-12-18', 'Open': 273.6, 'Close': 273.6},
 {'Date': '2025-12-17', 'Open': 275.01, 'Close': 275.01},
 {'Date': '2025-12-16', 'Open': 272.82, 'Close': 272.82},
 {'Date': '2025-12-15', 'Open': 280.15, 'Close': 280.15},
 {'Date': '2025-12-12', 'Open': 277.9, 'Close': 277.9},
 {'Date': '2025-12-11', 'Open': 279.1, 'Close': 279.1},
 {'Date': '2025-12-10', 'Open': 277.75, 'Close': 277.75},
 {'Date': '2025-12-09', 'Open': 278.16, 'Close': 278.16},
 {'Date': '2025-12-08', 'Open': 278.13, 'Close': 278.13},
 {'Date': '2025-12-05', 'Open': 280.54, 'Close': 280.54},
 {'Date': '2025-12-04', 'Open': 284.1, 'Close': 284.1},
 {'Date': '2025-12-03', 'Open': 286.2, 'Close': 286.2},
 {'Date': '2025-12-02', 'Open': 283.0, 'Close': 283.0},
 {'Date': '2025-12-01', 'Open': 278.01, 'Close': 278.01},
 {'Date': '2025-11-28', 'Open': 277.26, 'Close': 277.26},
 {'Date': '2025-11-26', 'Open': 276.96, 'Close': 276.96},
 {'Date': '2025-11-25', 'Open': 275.27, 'Close': 275.27},
 {'Date': '2025-11-24', 'Open': 270.9, 'Close': 270.9},
 {'Date': '2025-11-21', 'Open': 265.95, 'Close': 265.95},
 {'Date': '2025-11-20', 'Open': 270.83, 'Close': 270.83},
 {'Date': '2025-11-19', 'Open': 265.52, 'Close': 265.52},
 {'Date': '2025-11-18', 'Open': 269.99, 'Close': 269.99},
 {'Date': '2025-11-17', 'Open': 268.82, 'Close': 268.82},
 {'Date': '2025-11-14', 'Open': 271.05, 'Close': 271.05},
 {'Date': '2025-11-13', 'Open': 274.11, 'Close': 274.11},
 {'Date': '2025-11-12', 'Open': 275.0, 'Close': 275.0},
 {'Date': '2025-11-11', 'Open': 269.81, 'Close': 269.81},
 {'Date': '2025-11-10', 'Open': 268.96, 'Close': 268.96},
 {'Date': '2025-11-07', 'Open': 269.8, 'Close': 269.8},
 {'Date': '2025-11-06', 'Open': 267.89, 'Close': 267.89},
 {'Date': '2025-11-05', 'Open': 268.61, 'Close': 268.61},
 {'Date': '2025-11-04', 'Open': 268.32, 'Close': 268.32},
 {'Date': '2025-11-03', 'Open': 270.42, 'Close': 270.42}]

In [36]:
final_output

,open,high,low,close,volume,close_norm,retuens,pct_change
Date,,,,,,,,
2026-03-27,253.90,255.49,248.07,248.80,47899998,0.87,0.0000,0.00
2026-03-26,252.12,257.00,250.77,252.89,41796650,0.88,0.0164,1.64
2026-03-25,254.10,255.00,251.60,252.62,28476668,0.88,-0.0011,-0.11
2026-03-24,250.35,254.82,249.55,251.64,45152288,0.88,-0.0039,-0.39
2026-03-23,253.97,254.60,250.28,251.49,40546109,0.88,-0.0006,-0.06
...,...,...,...,...,...,...,...,...
2025-11-07,269.80,272.29,266.77,268.47,48227365,0.94,-0.0036,-0.36
2025-11-06,267.89,273.40,267.89,269.77,51204045,0.94,0.0048,0.48
2025-11-05,268.61,271.70,266.93,270.14,42586288,0.94,0.0014,0.14
2025-11-04,268.32,271.49,267.62,270.04,49274846,0.94,-0.0004,-0.04
2025-11-03,270.42,270.85,266.25,269.05,50194583,0.94,-0.0037,-0.37